spring:
  application:
    name: gateway
server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: http://localhost:8081/eureka
    fetch-registry: true
    register-with-eureka: true

zull:
    sensitive-headers: Cookie